# Generated by Django 4.0.1 on 2022-01-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_billinginformation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginformation',
            name='payment_status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='billinginformation',
            name='poll_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='billinginformation',
            name='phone',
            field=models.CharField(help_text='Ecocash Number - (e.g. 0776887606', max_length=10),
        ),
    ]
