# Generated by Django 4.0.1 on 2022-01-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_billinginformation_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginformation',
            name='payment_method',
            field=models.CharField(choices=[('ecocash', 'ECOCASH'), ('onemoney', 'ONE-MONEY')], default='ecocash', max_length=10),
        ),
    ]
