# Generated by Django 4.0.1 on 2022-01-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_billinginformation_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginformation',
            name='phone',
            field=models.CharField(help_text='Mobile Number - (e.g. 0776887606', max_length=10),
        ),
    ]
